import { defaultCanvasName } from "./constants/canvas";

export const demoTemplate = JSON.stringify({
  version: "5.3.0",
  objects: [
    {
      type: "rect",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 0,
      top: 0,
      width: 1000,
      height: 660,
      fill: "#ffffff",
      stroke: null,
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      rx: 0,
      ry: 0,
      id: "sketch-canvas",
      canvas_name: defaultCanvasName,
      selectable: false,
      hasControls: false,
    },
    {
      type: "f-image",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: -8.07,
      top: -11.26,
      width: 1225.03,
      height: 672.26,
      fill: "rgb(0,0,0)",
      stroke: null,
      strokeWidth: 0,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 0.96,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      objects: [
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 0,
          top: 0,
          width: 1880,
          height: 1031,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: true,
          strokeMiterLimit: 4,
          scaleX: 0.65,
          scaleY: 0.65,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "stroke",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            type: "rect",
            version: "5.3.0",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 1880,
            height: 1031,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: true,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "stroke",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
            inverted: false,
            absolutePositioned: false,
          },
          cropX: 0,
          cropY: 0,
          src: "https://images.pexels.com/photos/1249586/pexels-photo-1249586.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "rect",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 0,
          top: 0,
          width: 1880,
          height: 1031,
          fill: "#00000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: [],
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: true,
          strokeMiterLimit: 4,
          scaleX: 0.65,
          scaleY: 0.65,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
        },
      ],
    },
    {
      type: "rect",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 120.4,
      top: 89.8,
      width: 315.83,
      height: 200,
      fill: "#e0f7fa",
      stroke: "#000",
      strokeWidth: 0,
      strokeDashArray: [],
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 2.41,
      scaleY: 2.41,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 0.65,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      rx: 6,
      ry: 6,
      id: "5b5446d0-405a-4033-82f4-090f2b5a6d71",
      selectable: true,
      hasControls: true,
    },
    {
      type: "f-text",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 250,
      top: 107.85,
      width: 500,
      height: 28.25,
      fill: "#4d4d4d",
      stroke: null,
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      fontFamily: "Ubuntu Sans",
      fontWeight: "normal",
      fontSize: 25,
      text: "GET 50% OFF",
      underline: false,
      overline: false,
      linethrough: false,
      textAlign: "center",
      fontStyle: "normal",
      lineHeight: 1.3,
      textBackgroundColor: "",
      charSpacing: 80,
      styles: [],
      direction: "ltr",
      path: null,
      pathStartOffset: 0,
      pathSide: "left",
      pathAlign: "baseline",
      minWidth: 20,
      splitByGrapheme: false,
      id: "af8626b0-398a-42b4-89c1-dba85a64f534",
      selectable: true,
      hasControls: true,
    },
    {
      type: "f-text",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 238.63,
      top: 270.16,
      width: 500,
      height: 140.12,
      fill: "#000000",
      stroke: null,
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      fontFamily: "Signika Negative",
      fontWeight: "bold",
      fontSize: 124,
      text: "SALE",
      underline: false,
      overline: false,
      linethrough: false,
      textAlign: "center",
      fontStyle: "normal",
      lineHeight: 1.3,
      textBackgroundColor: "",
      charSpacing: 62,
      styles: [],
      direction: "ltr",
      path: null,
      pathStartOffset: 0,
      pathSide: "left",
      pathAlign: "baseline",
      minWidth: 20,
      splitByGrapheme: false,
      id: "412c9cda-6e97-4eb5-b837-9b910f0f4f13",
      selectable: true,
      hasControls: true,
    },
    {
      type: "f-text",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 315.83,
      top: 203.07,
      width: 345.59,
      height: 90.4,
      fill: "#000000",
      stroke: null,
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      fontFamily: "Abel",
      fontWeight: "normal",
      fontSize: 80,
      text: "SUMMER",
      underline: false,
      overline: false,
      linethrough: false,
      textAlign: "center",
      fontStyle: "normal",
      lineHeight: 1.3,
      textBackgroundColor: "",
      charSpacing: 122,
      styles: [],
      direction: "ltr",
      path: null,
      pathStartOffset: 0,
      pathSide: "left",
      pathAlign: "baseline",
      minWidth: 20,
      splitByGrapheme: false,
      id: "a79e3922-1e58-4106-88e7-333ffa1ae270",
      selectable: true,
      hasControls: true,
    },
    {
      type: "rect",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 392.75,
      top: 482.68,
      width: 211.5,
      height: 43.16,
      fill: "#BBDEFB",
      stroke: "#cdafed",
      strokeWidth: 4,
      strokeDashArray: [],
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      rx: 14,
      ry: 14,
      id: "bf6024b6-4343-48f0-ae91-506f29eb1358",
      selectable: true,
      hasControls: true,
    },
    {
      type: "f-text",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 423.41,
      top: 492.37,
      width: 153.19,
      height: 22.6,
      fill: "#9c1dd2",
      stroke: null,
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      fontFamily: "Mukta",
      fontWeight: "normal",
      fontSize: 20,
      text: " SHOP NOW",
      underline: false,
      overline: false,
      linethrough: false,
      textAlign: "center",
      fontStyle: "normal",
      lineHeight: 1.3,
      textBackgroundColor: "",
      charSpacing: 0,
      styles: [],
      direction: "ltr",
      path: null,
      pathStartOffset: 0,
      pathSide: "left",
      pathAlign: "baseline",
      minWidth: 20,
      splitByGrapheme: false,
      id: "f5badfd7-191f-4d33-9c97-e67b46e6e68f",
      selectable: true,
      hasControls: true,
    },
    {
      type: "polygon",
      version: "5.3.0",
      originX: "left",
      originY: "top",
      left: 380.78,
      top: 111.42,
      width: 21.56,
      height: 22.61,
      fill: "#c583e6",
      stroke: "#000",
      strokeWidth: 0,
      strokeDashArray: [],
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: true,
      strokeMiterLimit: 4,
      scaleX: 1.14,
      scaleY: 1.14,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "stroke",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      id: "ab64c180-e36b-4e14-a633-a3438a80dad9",
      selectable: true,
      hasControls: true,
      path: [
        ["M", 18.65, 2.85],
        ["L", 19.259999999999998, 6.71],
        ["L", 22.769999999999996, 8.5],
        ["L", 21, 12],
        ["L", 22.78, 15.5],
        ["L", 19.240000000000002, 17.29],
        ["L", 18.630000000000003, 21.15],
        ["L", 14.740000000000002, 20.54],
        ["L", 11.970000000000002, 23.299999999999997],
        ["L", 9.190000000000003, 20.499999999999996],
        ["L", 5.330000000000004, 21.139999999999997],
        ["L", 4.7100000000000035, 17.249999999999996],
        ["L", 1.2200000000000033, 15.469999999999997],
        ["L", 3, 11.97],
        ["L", 1.23, 8.5],
        ["L", 4.74, 6.6899999999999995],
        ["L", 5.3500000000000005, 2.8599999999999994],
        ["L", 9.22, 3.4999999999999996],
        ["L", 12, 0.69],
        ["L", 14.77, 3.46],
        ["z"],
        ["M", 9.5, 7],
        ["C", 8.67157287525381, 7, 8, 7.67157287525381, 8, 8.5],
        ["C", 8, 9.32842712474619, 8.67157287525381, 10, 9.5, 10],
        ["C", 10.32842712474619, 10, 11, 9.32842712474619, 11, 8.5],
        ["C", 11, 7.67157287525381, 10.32842712474619, 7, 9.5, 7],
        ["M", 14.5, 14],
        ["C", 13.67157287525381, 14, 13, 14.67157287525381, 13, 15.5],
        ["C", 13, 16.32842712474619, 13.67157287525381, 17, 14.5, 17],
        ["C", 15.32842712474619, 17, 16, 16.32842712474619, 16, 15.5],
        ["C", 16, 14.67157287525381, 15.32842712474619, 14, 14.5, 14],
        ["M", 8.41, 17],
        ["L", 17, 8.41],
        ["L", 15.59, 7],
        ["L", 7, 15.59],
        ["z"],
      ],
    },
  ],
  clipPath: {
    type: "rect",
    version: "5.3.0",
    originX: "left",
    originY: "top",
    left: 0,
    top: 0,
    width: 1000,
    height: 660,
    fill: "#ffffff",
    stroke: null,
    strokeWidth: 1,
    strokeDashArray: null,
    strokeLineCap: "butt",
    strokeDashOffset: 0,
    strokeLineJoin: "miter",
    strokeUniform: true,
    strokeMiterLimit: 4,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    flipX: false,
    flipY: false,
    opacity: 1,
    shadow: null,
    visible: true,
    backgroundColor: "",
    fillRule: "nonzero",
    paintFirst: "stroke",
    globalCompositeOperation: "source-over",
    skewX: 0,
    skewY: 0,
    rx: 0,
    ry: 0,
    selectable: true,
    hasControls: true,
  },
  background: "#ddd",
});
